### ISSUE TITLE
Good jobs! Some questions here.

### ISSUE THREAD

**Issue by DesmonDay** [Gaffey/ExCP#3]
Hello, I truly appreciate the work that has been done. Just wondering, have you conducted experiments on other LLMs, for example LLaMA, Qwen, etc. Or why you choose Pythia model?

**Comment by DesmonDay** [comment]
In addition, I am also curious whether this way of checkpoint compression will consume more time? Is there any specific experimental data?

**Comment by Gaffey** [comment]
Thanks for your interests of our work.
1. We choose Pythia model since it has different scales of models. Since running multiple training experiments is really expensive, we have to choose a small model like Pythia-410M. We also provide experimental results of PanGu-$\pi$ in our paper.
2. Take Pythia-410M as an example. All experiments are conducted on a server with Intel(R) Xeon(R) Platinum 8378A CPU and 8 GPUs. We use an independent process to deal with the compression process, which is running on the CPU only while the training process is running on the GPUs at the same time. Our method cost 16.3 seconds for compression and 8.1 seconds for reconstruction while the training process is undisturbed.

**Comment by DesmonDay** [comment]
The compression time seems a little bit slow. If the model size is large, like 7B, 20B, does the time consumed will increase according to the size of the model?

**Comment by Gaffey** [comment]
Sure, the time consumed will increase. But we don't need to interrupt the training when we do compression, and the compression process doesn't affect the training speed. As long as our compression can be completed before the next save, there is no burden on the training process. In fact, the time consumed is much less than the interval between two checkpoint saving operations.
