### ISSUE TITLE
Issuse with Hardcoded Optimizer ID Mapping

### ISSUE THREAD

**Issue by bothyouandme** [Gaffey/ExCP#4]
Dear ExCP authors,

We are currently attempting to follow your work, but due to GPU limitations, we are using a smaller model for our reproduction. During this process, we have encountered a few issues for which we hope to get your assistance.

Specifically, we noticed that the network layer weights and optimizer ID mappings are hardcoded in the `compress_pythia.py` file. The ID mappings are not in a common format, which has caused confusion for us in obtaining and modifying the mapping indexes for our adjusted model.

Could you please provide guidance on how to correctly map the indexes for the modified model? Any detailed instructions or resources would be greatly appreciated.

Thank you for your help!

Best regards.

**Comment by Gaffey** [comment]
Since we want the compression code to be decoupled from the training code, we can only take this hardcoded approach for now. You can print out the parameters by calling `named_parameter` after the model is built. Generally, this order corresponds to the order in which the optimizer is constructed (optimizer generally calls the `parameter` method). If the optimizer has groupings, further processing is required.

**Comment by bothyouandme** [comment]
Thank you for your prompt response. Indeed, our confusion stemmed from the grouping behavior when the transformer creates the default optimizer, which caused a mismatch between the order of network layer names returned by the `named_parameter` method and the optimizer ID sequence. We have resolved this issue by examining how the transformer constructs the default optimizer.

Thank you once again for your assistance!
Best regards.
